
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/alexnikita/treader/reader
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Reader_FRAMEWORK_H__
#define __Reader_FRAMEWORK_H__

#include "Reader.objc.h"
#include "universe.objc.h"

#endif
