// Objective-C API for talking to gitlab.com/alexnikita/treader/reader Go package.
//   gobind -lang=objc gitlab.com/alexnikita/treader/reader
//
// File is generated by gobind. Do not edit.

#ifndef __Reader_H__
#define __Reader_H__

@import Foundation;
#include "Universe.objc.h"


@class ReaderBook;

@interface ReaderBook : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)name;
- (void)setName:(NSString*)v;
@end

FOUNDATION_EXPORT NSString* const ReaderTYPE_EPUB;

// skipped function Open with unsupported parameter or return types


FOUNDATION_EXPORT long ReaderTest(void);

FOUNDATION_EXPORT BOOL ReaderValidate(NSData* file);

#endif
