// Objective-C API for talking to gitlab.com/alexnikita/treader/reader Go package.
//   gobind -lang=objc gitlab.com/alexnikita/treader/reader
//
// File is generated by gobind. Do not edit.

#ifndef __Reader_H__
#define __Reader_H__

@import Foundation;
#include "Universe.objc.h"


@class ReaderBook;

@interface ReaderBook : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)author;
- (void)setAuthor:(NSString*)v;
- (NSString*)title;
- (void)setTitle:(NSString*)v;
- (NSString*)coverpage;
- (void)setCoverpage:(NSString*)v;
- (NSString*)extension;
- (void)setExtension:(NSString*)v;
- (NSString*)hash;
- (void)setHash:(NSString*)v;
- (NSData*)get:(NSString*)href error:(NSError**)error;
- (BOOL)open:(NSData*)file error:(NSError**)error;
- (BOOL)spineNext;
- (NSString*)spineValue;
@end

FOUNDATION_EXPORT BOOL ReaderValidate(NSData* data);

#endif
