// Objective-C API for talking to gitlab.com/alexnikita/treader/reader Go package.
//   gobind -lang=objc gitlab.com/alexnikita/treader/reader
//
// File is generated by gobind. Do not edit.

#ifndef __Reader_H__
#define __Reader_H__

@import Foundation;
#include "Universe.objc.h"


@class ReaderBook;

@interface ReaderBook : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)author;
- (void)setAuthor:(NSString*)v;
- (NSString*)title;
- (void)setTitle:(NSString*)v;
- (NSString*)coverpage;
- (void)setCoverpage:(NSString*)v;
// skipped field Book.SpineStack with unsupported type: gitlab.com/alexnikita/treader/reader/parsers.SpineStack

- (NSString*)get:(long)count from:(long)from error:(NSError**)error;
- (BOOL)next;
- (BOOL)open:(NSData*)file error:(NSError**)error;
- (NSString*)value;
@end

FOUNDATION_EXPORT BOOL ReaderValidate(NSData* data);

#endif
